lib/grammar.js
incorrect parsing of offers from Chrome, which uses '; 'a space
character to separate parameters.
Chrome includes this line in created offers:
a=fmtp:111 minptime=10; useinbandfec=1
Parsing this loses the 'useinbandfec=1' parameter, because the reg exp does not include a space character.
I am not sure where the separator for parameters is defined (RFC4566 isn't clear about it, or at least I can't find), but the opus RTP payload type spec has [examples](https://tools.ietf.org/html/rfc7587#section-7) where parameters are indeed separated with '; '.
Including the ' ' in an offer to firefox doesn't seem to cause any problems.
=> Allows for a space in the list of parameters for a=fmtp lines. Fixes

lib/grammar.js, test/alac.sdp, test/parse.test.js
=> Treat rtpmap rate parameter as optional

lib/grammar.js
Seems tcptype is no working in the following example:
a=candidate:4 1 TCP 1688207359 192.0.2.3 9 typ srflx raddr 10.0.1.1 rport 9 tcptype active
Example taken from taken from http://tools.ietf.org/html/rfc6544#appendix-C.
(Credits to @bgrozev and @gpolitis)
=> Fixes tcptype with raddr and rport.

lib/parser.js, test/normal.sdp, test/parse.test.js
=> add support for base64 strings in fmtp

lib/grammar.js, test/normal.sdp, test/parse.test.js
see #40 
ssrc can supports attribute only without value
```
a=ssrc:<ssrc-id> <attribute>
a=ssrc:<ssrc-id> <attribute>:<value>
```
fix #40
=> fix ssrc: ssrc suppports attribute only

lib/grammar.js, test/normal.sdp, test/parse.test.js
current webrtc sdp will contain `network-id` and `network-cost` in the sdp.
these params still in draft.
**this PR only supports:**
* only `network-id` param
* only `network-cost` param
* both params with `network-id` first
**doesn't support:**
* both params with `network-cost` first
the draft example shows that `network-cost` can be put before `network-id`
but the actual sdp generate by webrtc is always `netword-id` first.
also, `network-id` is mandatory, but `network-cost` can be ignored if it is 0
Draft: https://tools.ietf.org/html/draft-thatcher-ice-network-cost-01
>    3.  Choosing a value for network cost and network ID
>       Network cost is an integer in the range 0-999, where larger values
>       indicate a stronger preference for not using that network interface.
>
> …
=> add supports for candidate attr: network-id / network-cost

lib/grammar.js
Fix for #53 
ssrc-group-attr = "ssrc-group:" semantics *(SP ssrc-id)
semantics       = "FEC" / "FID" / token
; Matches RFC 3388 definition and
; IANA registration rules in this doc.
token-char =          %x21 / %x23-27 / %x2A-2B / %x2D-2E / %x30-39
/ %x41-5A / %x5E-7E
token =               1*(token-char)
=> Fix for ssrc-group semantics parsing 

lib/grammar.js
Custom vendor attribute needed to make Chrome work in simulcast mode.
=> Add support for a=x-google-flag

README.md, lib/grammar.js, lib/index.js, lib/parser.js, test/parse.test.js, test/simulcast.sdp
* grammar: add `a=rid` attribute
* add a `simulcast.sdp` test
* add `exports.parseParams()` for generic attribute parameters and make `exports.parseFmtpConfig()` an alias
=> Support for a=rid and generic params parser

README.md, lib/grammar.js, lib/index.js, lib/parser.js, test/coverage.test.js, test/parse.test.js, test/simulcast.sdp
- grammar: add `imageattrs` for `a=imageattr` lines (RFC 6236)
- add `export.parseImageattrParams()`
=> Add support for a=imageattr (RFC 6236)

lib/grammar.js, test/normal.sdp, test/parse.test.js
Ran into a scenario where a `a=ssrc` line was not being parsed properly; the regex was not checking for `-` characters. The `ssrc` attribute in question is `previous-ssrc` ([RFC 5576](https://tools.ietf.org/html/rfc5576#section-6.2)).
This change modifies the `ssrc` grammar regex to allow for `-` in the attribute name, and adds a test case for it.
=> Add support for ssrc attributes with dashes.

lib/grammar.js, test/parse.test.js, test/st2022-6.sdp
grammar.js was missing an entry for "source-filter" as defined in RFC4570.
Last group in regex is a little bit greedy, but the RFC define it as "one or more unicast addresses or FQDNs, separated by space characters". 
I'm not a regex warrior, feel free to find a better implementation for that ;-)
=> add support for source-filter (ex: 'a=source-filter: incl IN IP4 239.5.2.31 10.1.15.5')

lib/grammar.js, test/hacky.sdp, test/parse.test.js
Adds support for `label` attribute per RFC 4574.
Resolves #74.
=> Adds support for label attribute per RFC 4574.

.npmrc, .travis.yml, lib/grammar.js, lib/parser.js, package.json, test/parse.test.js
* Add `.npmrc` to avoid `package-lock.json` generation.
* Make `grammar.js` comments more readable.
* Update `eslint` version.
* Remove unnecessary escape characters.
* Improve ternary operators readability.
* travis-ci: Use Node 6, 8 and 10 (avoid outdated Node 4)
=> Syntax improvements

README.md, lib/grammar.js, test/compose.test.js, test/coverage.test.js, test/extmap-encrypt.sdp, test/icelite.sdp, test/onvif.sdp, test/parse.test.js
`ext` entries get a new 'encrypt-uri' field which must be 'urn:ietf:params:rtp-hdrext:encrypt', meaning that the `a=extmap` entry indicates an encrypted header extension.
Some minor improvements have also been done, such as including missing SDP files in coverage tests.
=> Add support for encrypted header extensions (RFC 6904)

lib/parser.js
If there's only a payload in the m= line is considered as number and the function split throws an error.
Should check the other functions too
=> parsePayloads() is not safe

lib/grammar.js, test/compose.test.js, test/coverage.test.js, test/dante-aes67.sdp, test/parse.test.js
`a=keywds` is specified in [RFC4566](https://tools.ietf.org/html/rfc4566).
It is a session-level attribute.
The example SDP file was generated by a [Glensound AoIP44](https://www.glensound.co.uk/product-details/aoip44/) in [AES67 mode](https://en.wikipedia.org/wiki/AES67), which has a Dante Ultimo X4 chipset.
Note that the SDP also contains the following two lines. I will raise a further PR to add support for them:
```
a=ts-refclk:ptp=IEEE1588-2008:00-00-00-FF-FE-00-00-00:0
a=mediaclk:direct=3560866135
```
Full SDP in Gist here:
https://gist.github.com/njh/90e8b7f44f5c79a76a5e12cc922220c6
=> Add support for a=keywds

lib/grammar.js, test/compose.test.js, test/coverage.test.js, test/parse.test.js, test/tcp-active.sdp, test/tcp-passive.sdp
This Pull Request adds support for RFC4145 (TCP-Based Media Transport) to the grammar.
* `a=setup` was already in grammar.js
* I added `a=connection`, with 'new' and 'existing' as valid values
* I had to name the JavaScript property 'connectionType', because `c=` was getting written to `connection`
* Added a couple of example SDP files from based on the examples in RFC4145
Fixes #55
=> Added support for RFC4145 (TCP-Based Media Transport)

lib/grammar.js, test/normal.sdp, test/parse.test.js
New media section attribute: `extmapAllowMixed`.
* Spec: https://tools.ietf.org/html/rfc8285#section-6
* Reading:
```js
if (media[0].extmapAllowMixed)
{
// [...]
}
```
* Writing:
```js
media[0].extmapAllowMixed = 'extmap-allow-mixed';
```
=> Add support for a=extmap-allow-mixed (RFC 8285)

lib/grammar.js, test/hacky.sdp, test/parse.test.js
RFC-4566 states that `ptime` represents packet time in milliseconds, however I work with hardware that supports 110µs, 125µs, 1ms packet times which are being parsed as int's.
=> Feature - Add support for sub 1ms packet time

lib/grammar.js, test/compose.test.js, test/coverage.test.js, test/rtcp-fb.sdp
The [RFC-4585](https://tools.ietf.org/html/rfc4585) contains description of format rtcp-fb, rtcp-fb-pt could be "\*", but in grammar.js for trr-int value rtcp-fb-pt attribute couldn't be "\*". File test/rtcp-fb.sdp contains a real SDP from Linphone.
Without this fix after parse and write SDP from test/rtcp-fb.sdp file I get a wrong SDP with attributes like this: "a=rtcp-fb:NaN trr-int 5".
=> Fix rtcp-fb format for trr-int value

README.md
Fix the arguments of `parseSimulcastStreamList()` in the readme (resolves #95)
=> Fix README description of parseSimulcastStreamList()

README.md, lib/index.js
Hey!
This PR allows to mutate the grammar before parsing. This is useful when dealing with custom sdp attributes.
=> Expose grammar object for customisation
